### ISSUE TITLE
No tag exists for the 0.3.0 release

### ISSUE THREAD

**Issue by bcdickinson** [wagtail-nest/wagtail-airtable#39]
There's no corresponding tag/version bump in this repository for the 0.3.0 release on PyPI: https://pypi.org/project/wagtail-airtable/0.3.0/#files

**Comment by gasman** [comment]
Retrospectively added a tag, based on the release date. Looks like the version bump for 0.3.0 [never made it into the codebase](https://github.com/wagtail-nest/wagtail-airtable/commit/1c5e8f7d3761eb182ecd4a6a21d0d2d854a6be64) though...
