### ISSUE TITLE
wagtail_airtable/wagtail_hooks.py uses deprecated classnames when creating  a MenuItem

### ISSUE THREAD

**Issue by maliahavlicek** [wagtail-nest/wagtail-airtable#57]
### Issue Summary
I am in the process of upgrading a project to wagtail 5.2 and updated all custom menu items in my project from  **classnames=** to **classname=** but am still seeing the deprecation warning:
``` python
RemovedInWagtail60Warning: The `classnames` kwarg for MenuItem is deprecated - use `classname` instead.
```

### Relevant Information 
I have wagtail-airtable=0.6.0 installed, and when I put a breakpoint on the warning, I can see it traces back to wagtail-airtable:

![image](https://github.com/wagtail/wagtail-airtable/assets/23039742/9348b4d5-22f8-4762-89b0-5f2cfcae5798)

I believe if you change Line 29 of wagtail_airtable/wagtail_hooks.py to use classname the deprecation warning will go away.

### Technical details

-   Python version: 3.11.1.
-   Django version: 4.1.13
-   Wagtail version: 5.2
-   Wagtail Airtable version: 0.6.0
-   Browser version: Chrome 119

**Comment by gasman** [comment]
Thanks for the report @maliahavlicek! Have now opened #64 to address this - the preferred way to set the menu item icon is `icon_name="cog"` rather than setting class name directly.
