### ISSUE TITLE
API Keys can no longer access the Airtable API 

### ISSUE THREAD

**Issue by peteratdemtec** [wagtail-nest/wagtail-airtable#69]
Hi, 

According to https://support.airtable.com/docs/creating-personal-access-tokens and indeed my own experience, API Keys can no longer access the Airtable API. Attempting to use a personal access token by assigning it to the AIRTABLE_API_KEY setting fails with HTTP 401: Unauthorized, meaning this library is completely unusable until this is fixed.

Would it be possible to update this package to include support for personal access tokens?

**Comment by zerolab** [comment]
We're using an older SDK for Airtable - https://github.com/wagtail-nest/wagtail-airtable/blob/b0f58751ad7a5767a70e92da57f4f00a51fdf770/pyproject.toml#L36

It has now been renamed to [pyAirtable](https://pypi.org/project/pyairtable/) and is at version 2.x. The docs do mention the PATs - https://pyairtable.readthedocs.io/en/stable/getting-started.html

@KalobTaulien do you use Airtable in any active projects?

**Comment by gasman** [comment]
I've been using a personal access key as `AIRTABLE_BASE_KEY` with no issues. Have now updated the readme in d5f4e04e5f7cb535460d1ecc0ce41a92456cefb0 to document how to generate a key with the appropriate permissions.
